### ISSUE TITLE
How to remove that gray banner stating your browser is "unsupported"?

### ISSUE THREAD

**Issue by Dioxaz** [ZusorCode/GoodTwitter#41]
I'm asking that here because I couldn't find anything by searching on the internet the following message that displays on top of Twitter's page when I'm using the add-on:

> "You’re currently using an unsupported browser – for the best Twitter experience, please consider updating to Windows 10 or check the list of supported browsers."

![image](https://user-images.githubusercontent.com/5454404/74861773-31b7c080-534b-11ea-83aa-995edbc0abdf.png)

I don't know if this is by design or if this message shouldn't be here. I'm sorry if I missed something. Is there a FAQ of some kind? It's not that disturbing but still. I'd prefer not having to use the inspector each time I'm using Twitter with that add-on enabled.

Regards

**Comment by MistressBird** [comment]
I also had this issue, and I'd like to add that for me, Firefox and Windows 10 are both fully updated. I disabled and re-enabled the extension for the purposes of testing; disabling it removed the banner but put me back on the inferior Twitter format. Re-enabling the add-on did nothing; the extension no longer works.

**Comment by Amariithynar** [comment]
Thirding this issue. Was about to open my own on the topic, but was experimenting with settings to see if I could make it work. If I have GoodTwitter enabled, I can't even access Twitter at all, now; it gives me an error message about being unable to redirect to Twitter.

**Comment by MistressBird** [comment]
Evidence that I have an up-to-date Firefox and still get the banner.

![badtwitterbreaksgoodtwitter](https://user-images.githubusercontent.com/61247521/74862821-68251980-5312-11ea-8e7e-c63aeb00b589.png)

**Comment by cyberrufus** [comment]
Same issue here.

**Comment by FoxRoxB** [comment]
Same issue here. Tried hard refresh, clearing cache and cookies, desinstalling and reinstalling Good Twitter and the grey bar is still there. 
Firefox and Windows 10 up-to-date.

**Comment by DcSensai** [comment]
I also had this issue when i started firefox today.  just checked and its like that for chrome as well.

**Comment by Straga27** [comment]
Can confirm, also on the most up to date firefox version and an element picker to disable the banner does not work correctly as it removes more than the annoying banner

**Comment by daveinohio** [comment]
Same issue with Chrome version 80.0.3987.116. Tried signing out and back in to twitter, didn't work.

**Comment by kovahs** [comment]
Managed to get rid of the text by blocking the element with ublock origin (right click, block element) but its leaving a 'gap' So annoying but slightly less so.

![image](https://user-images.githubusercontent.com/61249120/74866442-ca9a0c00-534a-11ea-8795-e09dbcf30491.png)

**Comment by Amariithynar** [comment]
According to https://twitter.com/The_Petrichory/status/1230194636884340736 it's possible to deal with that by using Ublock Origin and entering these two lines:
> twitter.com##.Banner--aboveNav.Banner
> twitter.com#$#.topbar-spacer{ padding-top: 42px !important; }

Tested it for myself, and it worked! Had to do a hard refresh of the tab to refresh it, but it worked. This is still just a temporary fix, though.

**Comment by ZusorCode** [comment]
Fixed in 77610b32ff1a4d8122c076d8e7d407337f31f232

**Comment by DcSensai** [comment]
ive updated to the new software and it still isnt taking the banner away.

**Comment by DcSensai** [comment]
keeping an eye out for them to release a new release with the fix in there. until then using the above with ublock origin works fine.

**Comment by ZusorCode** [comment]
This is already released and live
